<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE practica [
	 <!ELEMENT autor (nombre, apellido1, apellido2)>
	 <!ELEMENT nombre (#PCDATA)>
	 <!ELEMENT apellido1 (#PCDATA)>
	 <!ELEMENT apellido2 (#PCDATA)>
	 <!ELEMENT usuario (id)>
	 <!ELEMENT asignatura (asig, anno)>
	 <!ELEMENT asig (#PCDATA)>
	 <!ELEMENT anno (#PCDATA)>
	 <!ELEMENT practica (autor*, asignatura)>
]>
<practica>
	<autor>
		<nombre>Diego</nombre>
		<apellido1>Sanchez </apellido1>
		<apellido2>Ramirez //</apellido2>
	</autor>

	<autor>
		<nombre> Jaime</nombre>
		<apellido1>Rodriguez</apellido1>
		<apellido2>Aguado //</apellido2>
	</autor>

	<asignatura>
		<asig> Gestion de Datos //</asig>
		<anno> 2018/2019</anno>
	</asignatura>

</practica>